name: DockerHub Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: "30 6,12 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: kyuubi2709/sunshine_pulse
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=edge,branch=main
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./images/sunshine  # Path to the directory containing the Dockerfile
          file: ./images/sunshine/Dockerfile  # Path to the Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_APP_IMAGE=ubuntu:24.04
            BASE_IMAGE=ubuntu:24.04
